GET http://34.116.192.77:2137/czy_oddycha
###

POST http://34.116.192.77:2137/v
Content-Type: application/json

{
  "platform": "tt",
  "url": "https://www.tiktok.com/@agagruntkow/video/7058750250751724805?is_copy_url=1&is_from_webapp=v1",
  "hash": "$2b$12$uvHvYlwwOI3BFDzcuQ0Nn.X4MpBaZsM0Qm/oBu7.CBGwOhHu3SXv6",
  "audio": 1
}
###

POST http://34.116.192.77:2137/v
Content-Type: application/json

{
  "platform": "ig",
  "url": "https://www.instagram.com/p/CZq7nouj13W/?utm_source=ig_web_copy_link",
  "hash": "$2b$12$uvHvYlwwOI3BFDzcuQ0Nn.X4MpBaZsM0Qm/oBu7.CBGwOhHu3SXv6",
  "audio": 1
}
###

POST http://34.116.192.77:2137/v
Content-Type: application/json

{
  "platform": "tt",
  "url": "https://www.tiktok.com/@koniu_koks/video/7059907610157387013?_d=secCgwIARCbDRjEFSACKAESPgo8%2B2fLf%2BLndVd81VU5MfXuQliNc6NF6c8Bqvy3zesVa4SroeiHJ1xQUZWMEAQmvAo0WZE84lHm7AOooMXPGgA%3D&language=pl&preview_pb=0&sec_user_id=MS4wLjABAAAAcP9XcvJ-dIO_VPsFqbkd2Bat7ifqHqIR275Vhv1p6cdvruyaMJO_9rQJ3EE6aIuL&share_app_id=1233&share_item_id=7059907610157387013&share_link_id=e424ee5e-3cde-4797-a391-a1d9a749daa3&source=h5_m&timestamp=1643882724&u_code=dbh7024e684844&user_id=6810021497744016390&utm_campaign=client_share&utm_medium=android&utm_source=copy&_r=1",
  "hash": "$2b$12$uvHvYlwwOI3BFDzcuQ0Nn.X4MpBaZsM0Qm/oBu7.CBGwOhHu3SXv6",
  "audio": 0
}
###